=head1 RAL

NEO-FORUM; FUTURE SOCIETY

=head2 EXECUTIVE SUMMARY

Forums are natural extensions of the Bulletin Board Systems (BBS) of last
century; posting on a traditional forum, you maintain an identity which
is attached to your screen name. RAL has no screen-names, no voting system,
and no reply counts; being widely-used is not a goal of RAL.

Moreover, the purpose is not to keep you coming back; we're not
interested in advertising or monetization. If you're a business looking
for forum software, this is definitely not for you.

The purpose of RAL is to create a network where you never confuse
ALTERNATE REALITY with VIRTUAL SELF

=head2 INSTALLATION / DEPENDENCIES

Refer to C<docs/INSTALL.pod> for the bloody details

=head2 CONTRIBUTING

Contributions are welcome! If you are interested in contributing, join
L<howler.space:6667|irc://howler.space:6667> #bigtown or L<send me an
e-mail|mailto:yumi@ral.space>. Further reading is available in
C<docs/HACKING.pod>

=head2 LICENSE

Modified BSD License (see C<docs/LICENSE>)
