=head1 RAL Neo-Forum

Textboard from a future society

=head2 Executive Summary

RAL is a text-only message board / forum. It provides a totally anonymous
discussion space on the internet; RAL is often called a neo-forum because it
takes inspiration from the classic forum model.

If you are curious what RAL feels like L<check out the
site|https://ral.space> (or access via
L<https://f22glwrndpxkacwp.onion|.onion>)

=head2 Installation / Dependencies

Refer to C<docs/INSTALL.pod> for the bloody details

=head2 Contributing

Contributions are welcome! If you are interested in contributing, join
L<howler.space:6667|irc://howler.space:6667> #bigtown or L<send me an
e-mail|mailto:yumi@ral.space>. Further reading is available in
C<docs/HACKING.pod>

=head2 License

Modified BSD License (see C<docs/LICENSE>)
